DROP DATABASE IF EXISTS BLOG;
CREATE DATABASE BLOG;
SHOW GRANTS FOR 'root'@'localhost';

CREATE USER 'USER'@'localhost' IDENTIFIED BY 'PASSWORD';

GRANT ALL PRIVILEGES ON BLOG.* TO 'USER'@'localhost';
